// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityManagementSystem.Data;

#nullable disable

namespace UniversityManagementSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityManagementSystem.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = 2,
                            InstructorId = 1,
                            Name = "Statistics"
                        },
                        new
                        {
                            Id = 2,
                            Credit = 4,
                            InstructorId = 1,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 3,
                            Credit = 3,
                            InstructorId = 3,
                            Name = "Public Adminstration"
                        },
                        new
                        {
                            Id = 4,
                            Credit = 3,
                            InstructorId = 4,
                            Name = "Pharmacology"
                        },
                        new
                        {
                            Id = 5,
                            Credit = 2,
                            InstructorId = 2,
                            Name = "Modern South Asia"
                        },
                        new
                        {
                            Id = 6,
                            Credit = 4,
                            InstructorId = 4,
                            Name = "Molecular Biology"
                        },
                        new
                        {
                            Id = 7,
                            Credit = 3,
                            InstructorId = 3,
                            Name = "Political Theory"
                        },
                        new
                        {
                            Id = 8,
                            Credit = 4,
                            InstructorId = 1,
                            Name = "Computer Architecture"
                        });
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aabdullah.university@gmail.com",
                            FirstName = "Adeel",
                            LastName = "Abdullah",
                            PhoneNumber = "8943216543"
                        },
                        new
                        {
                            Id = 2,
                            Email = "smohammed.university@gmail.com",
                            FirstName = "Sara",
                            LastName = "Mohammed",
                            PhoneNumber = "0982387612"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ribrahim.university@gmail.com",
                            FirstName = "Rand",
                            LastName = "Ibrahim",
                            PhoneNumber = "6709234789"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mabed.university@gmail.com",
                            FirstName = "Mourad",
                            LastName = "Abed",
                            PhoneNumber = "6122935902"
                        });
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollementYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollementYear = 2020,
                            FirstName = "Sara",
                            LastName = "Ahmad",
                            Major = "Biology",
                            PaymentStatus = true,
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            EnrollementYear = 2019,
                            FirstName = "Fahad",
                            LastName = "Abdullah",
                            Major = "Computer Science",
                            PaymentStatus = true,
                            PhoneNumber = "1876543289"
                        },
                        new
                        {
                            Id = 3,
                            EnrollementYear = 2021,
                            FirstName = "Yasser",
                            LastName = "Reda",
                            Major = "Politics",
                            PaymentStatus = true,
                            PhoneNumber = "1900124989"
                        },
                        new
                        {
                            Id = 4,
                            EnrollementYear = 2021,
                            FirstName = "Leena",
                            LastName = "Saad",
                            Major = "Politics",
                            PaymentStatus = true,
                            PhoneNumber = "7702127689"
                        },
                        new
                        {
                            Id = 5,
                            EnrollementYear = 2023,
                            FirstName = "Tala",
                            LastName = "Abdulmajeed",
                            Major = "History",
                            PaymentStatus = true,
                            PhoneNumber = "6890876511"
                        },
                        new
                        {
                            Id = 6,
                            EnrollementYear = 2023,
                            FirstName = "Fatima",
                            LastName = "Salman",
                            Major = "Nursing",
                            PaymentStatus = true,
                            PhoneNumber = "6194321489"
                        },
                        new
                        {
                            Id = 7,
                            EnrollementYear = 2022,
                            FirstName = "Saoud",
                            LastName = "Rakan",
                            Major = "Nursing",
                            PaymentStatus = true,
                            PhoneNumber = "1248765489"
                        },
                        new
                        {
                            Id = 8,
                            EnrollementYear = 2021,
                            FirstName = "Faris",
                            LastName = "Mohammed",
                            Major = "Software Engineering",
                            PaymentStatus = true,
                            PhoneNumber = "8245995101"
                        });
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 4,
                            Grade = "A"
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 6,
                            Grade = "C"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            Grade = "B"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            Grade = "C"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 8,
                            Grade = "B"
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3,
                            Grade = "C"
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 7,
                            Grade = "A"
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 3,
                            Grade = "A"
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 7,
                            Grade = "A"
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5,
                            Grade = "B"
                        });
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Course", b =>
                {
                    b.HasOne("UniversityManagementSystem.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.StudentCourse", b =>
                {
                    b.HasOne("UniversityManagementSystem.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityManagementSystem.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Course", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UniversityManagementSystem.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
